Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "DB configuration"
        Parameters: 
          - DBRootPassword
          - DBPassword
Parameters:
  DBRootPassword:
    NoEcho: 'true'
    Description: Root password for MySQL
    Type: String
    MinLength: '1'
    MaxLength: '41'
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password for wordpress MySQL database
    Type: String
    MinLength: '1'
    MaxLength: '41'
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must contain only alphanumeric characters.
Resources:
  RHELInstance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-01a76e79ae757048d
      KeyName: jz
      InstanceType: t2.micro
      SecurityGroupIds:
      - sg-03a3c99eecb49436d
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            yum install wget -y
            wget https://raw.githubusercontent.com/jzoid/aws-testing/master/install_wp.sh
            chmod u+x install_wp.sh
            ./install_wp.sh ${DBRootPassword} ${DBPassword}
            rm -rf ~/wordpress/ latest.tar.gz
